const leftList = document.getElementById('left-list')
const leftListTitle = document.getElementById('left-list-title')
const leftListItems = document.getElementById('left-list-items')
const leftInput = document.getElementById('left-list-input')
const leftButton = document.getElementById('left-list-button')
const rightList = document.getElementById('right-list')
const rightListTitle = document.getElementById('right-list-title')
const rightListItems = document.getElementById('right-list-items')
const rightInput = document.getElementById('right-list-input')
const rightButton = document.getElementById('right-list-button')

